<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="./views/assets/css/reset.css">
        <link rel="stylesheet" href="./views/assets/css/style.css">
        <title>RattaStrat : Plateform pour apprendre la stratégie dans pokemon</title>
    </head>
    <body>
        <header> 
            <div class="center-blocks">
                <div class="navigator">
                    <div class="left-nav">
                        <div class="logo">
                            <span>RattaStrat</span>
                        </div>
                        <nav>
                            <span><a href="pokedex.php">Pokédex</a></span>
                            <span>Equipe</span>
                            <span>Forum</span>
                            <span>Cours</span>
                            <span>CalculateurShodown</span>
                        </nav>
                    </div>
                    <div class="right-nav">
                        <span>S'identifer</span>
                        <span class="button-register">Inscription</span>
                    </div>
                </div>
            </div>
        </header>
        <main>
            <div class="center-blocks">
                <div class="container-hero">
                    <div class="center-texts">
                        <h1>APPREND LA STRATEGIE POKEMON EN T’AMUSANT</h1>
                        <span>1ère plateforme française à t'apprendre la stratégie Pokémon de manière ludique</span>
                        <div class="main-button">Nouvelle partie</div>
                    </div>
                    <div class="bottom-hero">
                        <div class="socials">
                            <i class="fab fa-twitter"></i>
                            <i class="fab fa-discord"></i>
                        </div>
                        <div class="arrow-down"><a href="#"><i class="fas fa-angle-down"></i></a></div>
                    </div>
                </div>
            </div>
            <img class="rattachen" src="./views/assets/image/Chentata.png" alt="professeur Rattachen">
            <div class="adventure-container">
                <img id="adventure" class="pikachu" src="./views/assets/image/pikachu.png" alt="Pikachu">
                <div class="center-texts">
                    <span>Tu désire apprendre ou comprendre ce qu’est la stratégie pokémon, mais tu ne sais pas ou commencer ?</span>
                    <h2>Sur <span>RattaStrat</span> tu apprend en jouant comme si tu démarrais une aventure pokemon</h2>
                </div>
                <div class="center-blocks">
                    <div class="advantages-container">
                        <div class="advantage"><div class="advantage-image"><img src="./views/assets/image/icons/cours.png" alt="cours"></div><span>Cours ludique</span></div>
                        <div class="advantage"><div class="advantage-image"><img src="./views/assets/image/icons/quiz.png" alt="quiz"></div><span>Quiz sympa pour s’entrainer</span></div>
                        <div class="advantage"><div class="advantage-image"><img src="./views/assets/image/icons/game.png" alt="game"></div><span>Mini jeux de mise en situation</span></div>
                        <div class="advantage"><div class="advantage-image"><img src="./views/assets/image/icons/level.png" alt="level"></div><span>Cours adapter au niveau de compte</span></div>
                    </div>
                </div>
            </div>
            <div class="call-action-container">
                <h2>L'aventure te tente ?</h2>
                <div class="button-call-act">Nouvelle partie</div>
            </div>
            <div class="actuality-container">
                <div class="center-blocks">
                    <h2>Actualité</h2>
                    <div class="container-articles">
                        <div class="infos current">
                            <div class="image-container"><img src="https://picsum.photos/500?random=1" alt="image"></div>
                            <h3>Inoguration du site RattaStrat 🎉</h3>
                            <span>par auteur  .  il y' a 3 jous</span>
                        </div>
                        <div class="infos">
                            <div class="image-container"><img src="https://picsum.photos/500?random=2" alt="image"></div>
                            <h3>Système de ranking sur RattaStrat </h3>
                            <span>par auteur  .  il y' a 3 jous</span>
                        </div>
                        <div class="infos">
                            <div class="image-container"><img src="https://picsum.photos/500?random=3" alt="image"></div>
                            <h3>Ce pokemon est “over power” !</h3>
                            <span>par auteur  .  il y' a 1 jous</span>
                        </div>
                    </div>
                    <div class="button-all-articles">
                        <span>Tout les articles</span>
                    </div>
                </div>
            </div>
            <div class="showcase-team-container">
                <div class="center-texts">
                    <h2>Équipe de la semaine</h2>
                    <p>Participer au show case de la meilleur équipe 
                        de la semaine en partageant une équipe ,la meilleur 
                        équipe est élu au vote par la communauté chaque fin de semain.
                    </p>
                </div>
                <div class="center-blocks">
                    <div class="team-container">

                    </div>
                </div>
            </div>
        </main>
        <footer>
            <ul>
                <div class="inline">
                    <li>Pokedex</li>
                    <li>Équipe</li>
                </div>
                <div class="inline">
                    <li>Forum</li>
                    <li>Cours</li>
                </div>
            </ul>
            <div class="bottom">
                <span>Paramètres des cookies</span>
                <span>Gérer les Données</span>
                <span>Centre de traitement des données personnelles</span>
                <span>Cookies</span>
                <span>Politique de protection des données personnelles</span>
                <span>Conditions d’utilisation</span>
            </div>
            <div class="copiright">
                <span>France</span>
                <span>© 2022 RattaStrat, Inc. Tous droits réservés</span>
            </div>
        </footer>
    </body>
    <script src="./views/assets/main.js" type="module"></script>
</html>
