<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="./views/assets/css/reset.css">
        <link rel="stylesheet" href="./views/assets/css/style.css">
        <title>RattaStrat : Plateform pour apprendre la stratégie dans pokemon</title>
    </head>
    <body>
        <header> 
            <div class="center-blocks">
                <div class="navigator">
                    <div class="left-nav">
                        <div class="logo">
                            <span>RattaStrat</span>
                        </div>
                        <nav>
                            <span><a href="pokedex.php">Pokédex</a></span>
                            <span>Equipe</span>
                            <span>Forum</span>
                            <span>Cours</span>
                            <span>CalculateurShodown</span>
                        </nav>
                    </div>
                    <div class="right-nav">
                        <span>S'identifer</span>
                        <span class="button-register">Inscription</span>
                    </div>
                </div>
            </div>
        </header>
        <main>
            <div class="main-container-pokedex">
                <h1>Pokédex</h1>
                <div class="container-pokedex">
                    <div class="left-side">
                        <div class="search-sort-container">
                           <div class="search-container">
                                <input type="text" name="" id="">
                           </div> 
                           <div class="sort-container">
                            <select name="Type" id="type-pokemon">
                                <option value="">type</option>
                                <option value="">feu</option>
                                <option value="">eau</option>
                                <option value="">vol</option>
                            </select>
                            <select name="Failblesse" id="weakness-pokemon">
                                <option value="">faiblesse</option>
                                <option value="">feu</option>
                                <option value="">eau</option>
                                <option value="">vol</option>
                            </select>
                            <select name="Abilité" id="ability-pokemon">
                                <option value="">abilité</option>
                                <option value="">Brasiée</option>
                                <option value="">Fer</option>
                                <option value="">Siphon</option>
                            </select>
                            <select name="taille" id="size-pokemon">
                                <option value="">taille</option>
                                <option value="">1.85m</option>
                                <option value="">5.6m</option>
                                <option value="">0.45m</option>
                            </select>
                            <select name="poids" id="weight-pokemon">
                                <option value="">poids</option>
                                <option value="">20kg</option>
                                <option value="">5.65.kg</option>
                                <option value="">10kg</option>
                            </select>
                           </div>
                        </div>
                        <div class="all-pokemon-container">
                            
                        </div>
                    </div>
                    <div class="right-side">

                    </div>
                </div>
            </div>
        </main>
        <footer>
            <ul>
                <div class="inline">
                    <li>Pokedex</li>
                    <li>Équipe</li>
                </div>
                <div class="inline">
                    <li>Forum</li>
                    <li>Cours</li>
                </div>
            </ul>
            <div class="bottom">
                <span>Paramètres des cookies</span>
                <span>Gérer les Données</span>
                <span>Centre de traitement des données personnelles</span>
                <span>Cookies</span>
                <span>Politique de protection des données personnelles</span>
                <span>Conditions d’utilisation</span>
            </div>
            <div class="copiright">
                <span>France</span>
                <span>© 2022 RattaStrat, Inc. Tous droits réservés</span>
            </div>
        </footer>
    </body>
    <script src="./views/assets/scriptPokedex.js" type="module"></script>
</html>
